APPNAME = 'LisuKeyboards'
VERSION = 0.3

for b in ('basic', 'standard') :
	kbd(target = 'kbds/lisu_' + b + '.kmn',
		source = 'lisu_' + b + '.kmn',
		font = 'Fonts/lisutzimu.ttf',
		mskbd = mskbd(capslockkeys="", lidinstall=[0x0436]),        # afrikaans
		fontname = 'LisuTzimu')
